# Pin npm packages by running ./bin/importmap

pin "application"
pin "confirm"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"

pin "@floating-ui/dom", to: "https://cdn.jsdelivr.net/npm/@floating-ui/dom@1.7.6/+esm"
pin "number-flow", to: "https://esm.sh/number-flow"
pin "number-flow/group", to: "https://esm.sh/number-flow/group"
pin "embla-carousel", to: "https://cdn.jsdelivr.net/npm/embla-carousel/embla-carousel.esm.js"
pin "embla-carousel-wheel-gestures", to: "https://cdn.jsdelivr.net/npm/embla-carousel-wheel-gestures@latest/+esm"
pin "tom-select", to: "https://cdn.jsdelivr.net/npm/tom-select@2.6.1/+esm"
pin "air-datepicker", to: "https://esm.sh/air-datepicker@3.6.0"
pin "air-datepicker/locale/en", to: "https://esm.sh/air-datepicker@3.6.0/locale/en"
pin "emoji-mart", to: "https://cdn.jsdelivr.net/npm/emoji-mart@latest/dist/browser.js"
pin "@emoji-mart/data", to: "https://cdn.jsdelivr.net/npm/@emoji-mart/data@latest/+esm"
pin "photoswipe", to: "https://cdn.jsdelivr.net/npm/photoswipe/dist/photoswipe.esm.js"
pin "motion", to: "https://cdn.jsdelivr.net/npm/motion@latest/+esm"
pin "@tiptap/core", to: "https://esm.sh/@tiptap/core@2.11.5"
pin "@tiptap/starter-kit", to: "https://esm.sh/@tiptap/starter-kit@2.11.5"
pin "@tiptap/extension-underline", to: "https://esm.sh/@tiptap/extension-underline@2.11.5"
pin "@tiptap/extension-link", to: "https://esm.sh/@tiptap/extension-link@2.11.5"
pin "@tiptap/extension-text-style", to: "https://esm.sh/@tiptap/extension-text-style@2.11.5"
pin "@tiptap/extension-color", to: "https://esm.sh/@tiptap/extension-color@2.11.5"
pin "@tiptap/extension-image", to: "https://esm.sh/@tiptap/extension-image@2.11.5"
pin "@tiptap/extension-text-align", to: "https://esm.sh/@tiptap/extension-text-align@2.11.5"
