require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Raise delivery errors so a broken SMTP setup is visible rather than silent.
  config.action_mailer.raise_delivery_errors = true

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates. A "localhost:3000" URL
  # embedded in a mailer-generated link/image can only ever resolve for requests originating from
  # this machine - never for a real external recipient. To test real delivery (e.g. campaign
  # images) against a public tunnel (ngrok, Cloudflare Tunnel, etc.) pointed at this dev server,
  # run with APP_HOST set instead, e.g.: APP_HOST=abc123.ngrok-free.app bin/dev
  config.action_mailer.default_url_options = if ENV["APP_HOST"]
    { host: ENV["APP_HOST"], protocol: ENV.fetch("APP_PROTOCOL", "https") }
  else
    { host: "localhost", port: 3000 }
  end

  # Azure Communication Services SMTP relay - see config/credentials.example for the
  # azure_email credentials this reads.
  config.action_mailer.smtp_settings = {
    address:              "smtp.azurecomm.net",
    port:                 587,
    domain:               "rxterminal.co.uk",
    user_name:            Rails.application.credentials.dig(:azure_email, :smtp_username),
    password:             Rails.application.credentials.dig(:azure_email, :smtp_password),
    authentication:       :login,
    enable_starttls_auto: true
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
